### ISSUE TITLE
Doctests issues

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/linear-accelerate#5]
I'm opening this issue for a couple of reasons:

* [x] (Edit: resolved in https://github.com/ekmett/linear-accelerate/pull/6) `linear-accelerate` currently doesn't build with `Cabal-1.25` (which is bundled with GHC 8.2), since it causes the `Setup.hs` script to break:

   ```
   $ cabal configure -w /opt/ghc/8.2.1/bin/ghc
   Resolving dependencies...
   Warning: solver failed to find a solution:
   Could not resolve dependencies:
   trying: linear-accelerate-0.3 (user goal)
   next goal: linear (dependency of linear-accelerate-0.3)
   Dependency tree exhaustively searched.
   Trying configure anyway.
   [1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
   
   dist/setup/setup.hs:8:31: error:
       Module
       ‘Distribution.Package’
       does not export
       ‘PackageName(PackageName)’
     |
   8 | import Distribution.Package ( PackageName(PackageName), PackageId, InstalledPackageId, packageVersion, packageName )
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^
   ```

   See also https://github.com/ekmett/lens/issues/709, where we identified other packages with similar issues. Fixing this is quite easy with `cabal-doctest`. However...

* [ ] `linear-accelerate` has doctests, but they aren't used! Moreover, I tried running the doctests in this package recently, but it resulted in many failures. It didn't seem like fixing the doctests would be a simple matter, either.

We should fix these separately, as the former task will likely be far easier than the latter.
